### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by jaeminoh** [JinshuaiBai/PIRBN#1]
Hello!

I'd like to run your code, (especially the 1d sine function - NTK, which looks pretty interesting)
but even though I installed the most recent Tensorflow, I failed.
Could you please add `requirements.txt` to specify the versions of related packages?

Thanks!

**Comment by JinshuaiBai** [comment]
Hey Jaeminoh,

Many thanks for your suggestion. I have now added a "requirements.txt".
However, this is my very first time preparing a "requirments.txt"; I am unsure if it can work.
Please let me know if you have any further issues.

Best regards,
Jinshuai Bai

**Comment by jaeminoh** [comment]
If you are using Conda, `conda env export > environment.yml` exports your Conda environment.
I could run your code based on `requirements.txt`, with a tiny workaround that installs `python=3.9` and `protobuf=3.20.1`.

Thanks for the quick feedback!
